version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://sectracker:${DB_PASSWORD:-SecTracker2024!}@db:5432/sectracker
      - SESSION_SECRET=${SESSION_SECRET:-defaultsecret}
      - FLASK_APP=app.py
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=sectracker
      - POSTGRES_PASSWORD=${DB_PASSWORD:-SecTracker2024!}
      - POSTGRES_DB=sectracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sectracker"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge