version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://sectracker:${DB_PASSWORD:-SecTracker2024!}@db:5432/sectracker
      - SESSION_SECRET=${SESSION_SECRET:-defaultsecret}
      - FLASK_APP=app.py
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=sectracker
      - POSTGRES_PASSWORD=${DB_PASSWORD:-SecTracker2024!}
      - POSTGRES_DB=sectracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge