version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://sectracker:SecTracker2024!@db:5433/sectracker
      - SESSION_SECRET=${SESSION_SECRET:-defaultsecret}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    depends_on:
      - db
    restart: always
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=sectracker
      - POSTGRES_PASSWORD=SecTracker2024!
      - POSTGRES_DB=sectracker
      - PGPORT=5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sectracker -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: